name: ansible-lint
on:
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    name: Ansible Lint on PR
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v5
        with:
          ref: ${{ github.ref }}

      - name: Run ansible-lint
        uses: ansible/ansible-lint@main
